version: '3'

services:
  drone-server:
    image: drone/drone:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/lib/drone:/data
    environment:
      - DRONE_GITHUB_CLIENT_ID=Ov23liJSPj8UGqPUJGXq
      - DRONE_GITHUB_CLIENT_SECRET=62102904cd384c934a2d4fb1813c161c23ac452b
      - DRONE_RPC_SECRET=c86548bf9dbe311d90dad52d2d533428
      - DRONE_SERVER_HOST=http://drone.domain.com
      - DRONE_SERVER_PROTO=https
    restart: always

  drone-runner:
    image: drone/drone-runner-docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_PROTO=https
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_SECRET=c86548bf9dbe311d90dad52d2d533428
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=my-runner
    restart: always
